<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>DocTools</RootNamespace>
    <AssemblyName>DocTools</AssemblyName>
    <Version>0.3.0</Version>
  </PropertyGroup>

</Project>